CREATE TABLE [import].[CONTACT] (
	[CONTACT_KEY] INT NOT NULL
		CONSTRAINT [DF_CONTACT_CONTACT_KEY_SEQUENCE] DEFAULT (NEXT VALUE FOR [import].[CONTACT_KEY]), 
    [IMPORT_FILE_KEY] int,
    [FULL_NAME_AND_ADDRESS] varchar(200),
    [PHONE] varchar(50),
    [EMAIL] varchar(50)
)

