CREATE TABLE [stage].[CONTACT_NAME_AND_ADDRESS] (
    [IMPORT_FILE_KEY] int,
    [FULL_NAME_AND_ADDRESS] varchar(200),
    [CONTACT_KEY] int,
    [MD_Results] nvarchar(200),
    [MD_AddressExtras] nvarchar(50),
    [MD_AddressKey] nvarchar(11),
    [MD_AddressLine1] nvarchar(50),
    [MD_AddressLine2] nvarchar(50),
    [MD_City] nvarchar(35),
    [MD_CompanyName] nvarchar(128),
    [MD_NameFull] nvarchar(255),
    [MD_PostalCode] nvarchar(10),
    [MD_State] nvarchar(15),
    [MD_Latitude] nvarchar(24),
    [MD_Longitude] nvarchar(24),
    [MD_Gender] nvarchar(1),
    [MD_NameFirst] nvarchar(35),
    [MD_NameLast] nvarchar(35),
    [MD_NameMiddle] nvarchar(20),
    [MD_NamePrefix] nvarchar(20),
    [MD_NameSuffix] nvarchar(20),
    [MD_Salutation] nvarchar(20)
)